Require PHP >= 8.2
Here is incompatibility with `iterator_to_array()` before PHP 8.2
```
TypeError: iterator_to_array(): Argument #1 ($iterator) must be of type Traversable, array given
```